import type { LeaderboardEntry, PublicStats } from "./types";

export const demoLeaderboard: LeaderboardEntry[] = [
  {
    id: "demo-1",
    globalRank: 1,
    slug: "kinh-mat-viet",
    originalUrl: "https://example.com/kinh-mat-viet",
    canonicalUrl: "https://example.com/kinh-mat-viet",
    domain: "example.com",
    title: "Kính Mắt Việt",
    description: "Gọng kính và kính râm được tuyển chọn cho phong cách hằng ngày.",
    imageUrl: null,
    faviconUrl: null,
    totalPaid: 2_500_000,
    clickCount: 1_248,
    firstPaidAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    lastPaidAt: new Date(Date.now() - 3600000).toISOString(),
    provinces: [{ id: "demo-ha-noi", slug: "ha-noi", name: "Hà Nội", rank: 1 }],
  },
  {
    id: "demo-2",
    globalRank: 2,
    slug: "the-gioi-gong",
    originalUrl: "https://example.org/gong-kinh",
    canonicalUrl: "https://example.org/gong-kinh",
    domain: "example.org",
    title: "Thế Giới Gọng",
    description: "Gọng kính tối giản, nhẹ và phù hợp với nhiều dáng khuôn mặt.",
    imageUrl: null,
    faviconUrl: null,
    totalPaid: 1_200_000,
    clickCount: 736,
    firstPaidAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    lastPaidAt: new Date(Date.now() - 7200000).toISOString(),
    provinces: [{ id: "demo-ho-chi-minh", slug: "ho-chi-minh", name: "Thành phố Hồ Chí Minh", rank: 1 }],
  },
  {
    id: "demo-3",
    globalRank: 3,
    slug: "sunny-eyewear",
    originalUrl: "https://example.net/sunglasses",
    canonicalUrl: "https://example.net/sunglasses",
    domain: "example.net",
    title: "Sunny Eyewear",
    description: "Kính râm chống UV với thiết kế hiện đại.",
    imageUrl: null,
    faviconUrl: null,
    totalPaid: 650_000,
    clickCount: 421,
    firstPaidAt: new Date(Date.now() - 86400000).toISOString(),
    lastPaidAt: new Date(Date.now() - 10800000).toISOString(),
    provinces: [{ id: "demo-da-nang", slug: "da-nang", name: "Đà Nẵng", rank: 1 }],
  },
];

export const demoStats: PublicStats = {
  totalVisitors: 24_581,
  totalPageviews: 73_920,
  totalOutboundClicks: 9_842,
  totalRevenue: 4_350_000,
};
